/*
 * JFrmPrincipal.java
 *
 * Created on 8 de Agosto de 2008, 09:47
 */
package br.sca.view;

import br.sca.util.PanelFactory;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemAluno = new javax.swing.JMenuItem();
        jMenuItemCurso = new javax.swing.JMenuItem();
        jMenuItemDisciplina = new javax.swing.JMenuItem();
        jMenuItemProfessor = new javax.swing.JMenuItem();
        jMenuItemTurma = new javax.swing.JMenuItem();
        jMenuItemAutomovel = new javax.swing.JMenuItem();
        jMenuRotinas = new javax.swing.JMenu();
        jMenuItemMatricula = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemFinalizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCA");

        jTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneMouseClicked(evt);
            }
        });
        jTabbedPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPaneKeyPressed(evt);
            }
        });

        jMenuCadastro.setMnemonic('C');
        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setBorderPainted(true);
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });

        jMenuItemAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sca/resources/propr.png"))); // NOI18N
        jMenuItemAluno.setText("Aluno");
        jMenuItemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlunoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemAluno);

        jMenuItemCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCurso.setText("Curso");
        jMenuItemCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCursoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCurso);

        jMenuItemDisciplina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDisciplina.setText("Disciplina");
        jMenuItemDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDisciplinaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemDisciplina);

        jMenuItemProfessor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemProfessor.setText("Professor");
        jMenuItemProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfessorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemProfessor);

        jMenuItemTurma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTurma.setText("Turma");
        jMenuItemTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTurmaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemTurma);

        jMenuItemAutomovel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAutomovel.setText("Automóvel");
        jMenuItemAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutomovelActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemAutomovel);

        jMenuBar.add(jMenuCadastro);

        jMenuRotinas.setMnemonic('R');
        jMenuRotinas.setText("Rotinas");

        jMenuItemMatricula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemMatricula.setText("Matrícula");
        jMenuItemMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMatriculaActionPerformed(evt);
            }
        });
        jMenuRotinas.add(jMenuItemMatricula);

        jMenuBar.add(jMenuRotinas);

        jMenuRelatorios.setMnemonic('e');
        jMenuRelatorios.setText("Relatórios");
        jMenuBar.add(jMenuRelatorios);

        jMenuSair.setMnemonic('S');
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuItemFinalizar.setText("Finalizar Aplicação");
        jMenuItemFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinalizarActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemFinalizar);

        jMenuBar.add(jMenuSair);

        setJMenuBar(jMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItemFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinalizarActionPerformed
    if (JOptionPane.showConfirmDialog(this, 
            "Deseja Finalizar Aplicação?", "ATENÇÂO ",
            JOptionPane.YES_NO_OPTION) == 0) {
        System.exit(0);
    }
}//GEN-LAST:event_jMenuItemFinalizarActionPerformed

private void jMenuItemCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCursoActionPerformed
    int j;
    boolean ok;
    for (ok = false, j = 0; !ok && j < jTabbedPane.getTabCount(); j++) {
        if (jTabbedPane.getTitleAt(j).contentEquals("Cursos")) {
            jTabbedPane.setSelectedIndex(j);
            ok = true;
        }
    }
    if (!ok) {
        jTabbedPane.add("Cursos", PanelFactory.getPanel("Cursos", this));
        jTabbedPane.setSelectedIndex(jTabbedPane.getTabCount() - 1);
        jTabbedPane.getSelectedComponent().requestFocus();
    }

}//GEN-LAST:event_jMenuItemCursoActionPerformed

private void jTabbedPaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPaneKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        if (jTabbedPane.getSelectedIndex() > -1) {
            jTabbedPane.remove(jTabbedPane.getSelectedIndex());
        }
    }
}//GEN-LAST:event_jTabbedPaneKeyPressed

private void jMenuItemDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDisciplinaActionPerformed
    int j;
    boolean ok;
    for (ok = false, j = 0; !ok && j < jTabbedPane.getTabCount(); j++) {
        if (jTabbedPane.getTitleAt(j).contentEquals("Disciplinas")) {
            jTabbedPane.setSelectedIndex(j);
            ok = true;
        }
    }
    if (!ok) {
        jTabbedPane.add("Disciplinas", PanelFactory.getPanel("Disciplinas", this));
        jTabbedPane.setSelectedIndex(jTabbedPane.getTabCount() - 1);
        jTabbedPane.getSelectedComponent().requestFocus();
    }

}//GEN-LAST:event_jMenuItemDisciplinaActionPerformed

private void jTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMouseClicked
    jTabbedPane.getSelectedComponent().requestFocus();
}//GEN-LAST:event_jTabbedPaneMouseClicked

private void jMenuItemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlunoActionPerformed
    int j;
    boolean ok;
    for (ok = false, j = 0; !ok && j < jTabbedPane.getTabCount(); j++) {
        if (jTabbedPane.getTitleAt(j).contentEquals("Alunos")) {
            jTabbedPane.setSelectedIndex(j);
            ok = true;
        }
    }
    if (!ok) {
        jTabbedPane.add("Alunos", PanelFactory.getPanel("Alunos", this));
        jTabbedPane.setSelectedIndex(jTabbedPane.getTabCount() - 1);
        jTabbedPane.getSelectedComponent().requestFocus();
    }
}//GEN-LAST:event_jMenuItemAlunoActionPerformed

private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jMenuCadastroActionPerformed

private void jMenuItemProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfessorActionPerformed
    int j;
    boolean ok;
    for (ok = false, j = 0; !ok && j < jTabbedPane.getTabCount(); j++) {
        if (jTabbedPane.getTitleAt(j).contentEquals("Professores")) {
            jTabbedPane.setSelectedIndex(j);
            ok = true;
        }
    }
    if (!ok) {
        jTabbedPane.add("Professores", PanelFactory.getPanel("Professores", this));
        jTabbedPane.setSelectedIndex(jTabbedPane.getTabCount() - 1);
        jTabbedPane.getSelectedComponent().requestFocus();
    }

}//GEN-LAST:event_jMenuItemProfessorActionPerformed

private void jMenuItemTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurmaActionPerformed
    int j;
    boolean ok;
    for (ok = false, j = 0; !ok && j < jTabbedPane.getTabCount(); j++) {
        if (jTabbedPane.getTitleAt(j).contentEquals("Turmas")) {
            jTabbedPane.setSelectedIndex(j);
            ok = true;
        }
    }
    if (!ok) {
        jTabbedPane.add("Turmas", PanelFactory.getPanel("Turmas", this));
        jTabbedPane.setSelectedIndex(jTabbedPane.getTabCount() - 1);
        jTabbedPane.getSelectedComponent().requestFocus();
    }

}//GEN-LAST:event_jMenuItemTurmaActionPerformed

private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jMenuSairActionPerformed

private void jMenuItemMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMatriculaActionPerformed
    int j;
    boolean ok;
    for (ok = false, j = 0; !ok && j < jTabbedPane.getTabCount(); j++) {
        if (jTabbedPane.getTitleAt(j).contentEquals("Matrícula")) {
            jTabbedPane.setSelectedIndex(j);
            ok = true;
        }
    }
    if (!ok) {
        jTabbedPane.add("Matrícula", PanelFactory.getPanel("Matrícula", this));
        jTabbedPane.setSelectedIndex(jTabbedPane.getTabCount() - 1);
        jTabbedPane.getSelectedComponent().requestFocus();
    }

}//GEN-LAST:event_jMenuItemMatriculaActionPerformed

    private void jMenuItemAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutomovelActionPerformed
        int j;
        boolean ok;
        for (ok = false, j = 0; !ok && j < jTabbedPane.getTabCount(); j++) {
            if (jTabbedPane.getTitleAt(j).contentEquals("Automóvel")) {
                jTabbedPane.setSelectedIndex(j);
                ok = true;
            }
        }
        if (!ok) {
            jTabbedPane.add("Automóvel", PanelFactory.getPanel("Automóvel", this));
            jTabbedPane.setSelectedIndex(jTabbedPane.getTabCount() - 1);
            jTabbedPane.getSelectedComponent().requestFocus();
        }
    }//GEN-LAST:event_jMenuItemAutomovelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAluno;
    private javax.swing.JMenuItem jMenuItemAutomovel;
    private javax.swing.JMenuItem jMenuItemCurso;
    private javax.swing.JMenuItem jMenuItemDisciplina;
    private javax.swing.JMenuItem jMenuItemFinalizar;
    private javax.swing.JMenuItem jMenuItemMatricula;
    private javax.swing.JMenuItem jMenuItemProfessor;
    private javax.swing.JMenuItem jMenuItemTurma;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuRotinas;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
